# Generated by Django 4.2.5 on 2024-01-08 01:34

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, verbose_name='地域名')),
                ('area_supplement', models.TextField(blank=True, null=True, verbose_name='補足')),
                ('water_gate_map', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=80, scale=1, size=[1000, 800], upload_to='', verbose_name='地図大画像')),
                ('water_gate_map_sm', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=80, scale=1, size=[300, 240], upload_to='', verbose_name='地図小画像')),
            ],
            options={
                'verbose_name': 'wg_area (地域)',
                'verbose_name_plural': 'wg_area (地域)',
                'db_table': 'wg_area',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_name', models.CharField(max_length=20, verbose_name='都道府県')),
            ],
            options={
                'verbose_name': 'wg_prefecture (都道府県)',
                'verbose_name_plural': 'wg_prefecture (都道府県)',
                'db_table': 'wg_prefecture',
            },
        ),
        migrations.CreateModel(
            name='WaterGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_gate_no', models.CharField(max_length=10, verbose_name='扉番号')),
                ('water_gate_name', models.CharField(max_length=50, verbose_name='扉名')),
                ('water_gateaddress', models.CharField(max_length=256, verbose_name='扉住所')),
                ('water_gate_supplement', models.TextField(blank=True, null=True, verbose_name='補足')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area', verbose_name='地域')),
            ],
            options={
                'verbose_name': 'wg_base (水門・陸閘)',
                'verbose_name_plural': 'wg_base (水門・陸閘)',
                'db_table': 'wg_base',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prefecture'),
        ),
    ]
