# Generated by Django 4.2.5 on 2024-02-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100, verbose_name='名称')),
                ('system_value', models.TextField(blank=True, null=True, verbose_name='値')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '【マスタ】1.システム情報',
                'db_table': 'wg_system_info',
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': '【マスタ】3.地域'},
        ),
        migrations.AlterModelOptions(
            name='classinfo',
            options={'verbose_name_plural': '【マスタ】4.分類情報'},
        ),
        migrations.AlterModelOptions(
            name='prefecture',
            options={'verbose_name_plural': '【マスタ】2.都道府県'},
        ),
        migrations.AlterModelOptions(
            name='statusinfo',
            options={'verbose_name_plural': '【マスタ】5.ステータス情報'},
        ),
    ]
