# Generated by Django 4.2.5 on 2024-03-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevice',
            name='is_disp',
            field=models.BooleanField(default=True, verbose_name='画面表示'),
        ),
        migrations.AlterField(
            model_name='enddevicedata',
            name='send_kind',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='送受種別'),
        ),
    ]
