# Generated by Django 4.2.5 on 2024-03-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevicedata',
            name='gate_status',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='ゲート状態'),
        ),
    ]
