# Generated by Django 4.2.5 on 2024-01-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enddevicedata_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevice',
            name='dev_eui',
            field=models.CharField(max_length=20, verbose_name='エンドデバイスID(deveui)'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gw_id',
            field=models.CharField(max_length=20, verbose_name='LoRaSPNゲートウェイID(gwid)'),
        ),
    ]
