# Generated by Django 4.2.5 on 2024-02-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systeminfo_alter_area_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='system_value',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='値'),
        ),
    ]
