# Generated by Django 4.2.5 on 2024-03-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enddevicedata_gate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevicedata',
            name='battery_level',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='電池残量'),
        ),
        migrations.AlterField(
            model_name='enddevicedata',
            name='com_status',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='通信状況'),
        ),
    ]
