# Generated by Django 4.2.5 on 2023-09-27 22:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_watergate_water_gate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watergate',
            name='water_gate_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.9, size=[600, 600], upload_to='', verbose_name='画像'),
        ),
    ]
