# Generated by Django 4.2.5 on 2024-02-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_enddevice_dev_eui_alter_gateway_gw_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enddevicedata',
            old_name='gate_battery_level',
            new_name='battery_level',
        ),
        migrations.RenameField(
            model_name='enddevicedata',
            old_name='gate_communication',
            new_name='com_status',
        ),
    ]
