# Generated by Django 4.2.5 on 2024-02-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_gate_battery_level_enddevicedata_battery_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevicedata',
            name='battery_level',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='電池残量(0:良, 1:低下)'),
        ),
        migrations.AlterField(
            model_name='enddevicedata',
            name='com_status',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='通信状況(0:未受信, 1:不良, 2:普通, 3:良好)'),
        ),
        migrations.AlterField(
            model_name='enddevicedata',
            name='gate_status',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='ゲート状態(0:消灯-open, 1:全閉-close)'),
        ),
    ]
