# Generated by Django 4.2.5 on 2023-09-27 23:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_watergate_water_gate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='watergate',
            name='water_gate_image_sm',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1, size=[500, 400], upload_to='', verbose_name='モバイル画像'),
        ),
        migrations.AlterField(
            model_name='watergate',
            name='water_gate_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1, size=[500, 400], upload_to='', verbose_name='PC画像'),
        ),
    ]
