# Generated by Django 4.2.5 on 2023-09-27 23:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_watergate_water_gate_image_sm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watergate',
            name='water_gate_image_sm',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1, size=[200, 200], upload_to='', verbose_name='モバイル画像'),
        ),
    ]
