# Generated by Django 4.2.5 on 2024-02-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_enddevicedata_battery_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='分類名')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '【マスタ】3.分類情報',
                'db_table': 'wg_class_info',
            },
        ),
        migrations.CreateModel(
            name='StatusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=10, verbose_name='ステータスコード')),
                ('status_name', models.CharField(max_length=100, verbose_name='ステータス名')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classinfo')),
            ],
            options={
                'verbose_name_plural': '【マスタ】4.ステータス情報',
                'db_table': 'wg_status_info',
            },
        ),
    ]
