# Generated by Django 4.2.5 on 2024-02-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_classinfo_statusinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusinfo',
            name='status_supplement',
            field=models.TextField(blank=True, null=True, verbose_name='補足'),
        ),
    ]
