# Generated by Django 4.2.5 on 2023-09-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_watergate_water_gate_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watergate',
            name='water_gate_latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='watergate',
            name='water_gate_longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13, verbose_name='経度'),
        ),
    ]
