# Generated by Django 4.2.5 on 2024-02-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_statusinfo_status_supplement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enddevice',
            options={'verbose_name_plural': '【機器】2.エンドデバイス'},
        ),
        migrations.AlterModelOptions(
            name='enddevicedata',
            options={'verbose_name_plural': '【機器】3.エンドデバイス受信データ'},
        ),
        migrations.AlterModelOptions(
            name='gateway',
            options={'verbose_name_plural': '【機器】1.ゲートウェイ'},
        ),
    ]
