# Generated by Django 4.2.5 on 2023-09-28 05:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_watergate_water_gate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watergate',
            name='water_gate_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1, size=[500, 400], upload_to='', verbose_name='大画像'),
        ),
    ]
