# Generated by Django 4.2.5 on 2023-10-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_watergate_water_gate_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watergate',
            name='water_gate_latitude',
        ),
        migrations.RemoveField(
            model_name='watergate',
            name='water_gate_longitude',
        ),
        migrations.AddField(
            model_name='watergate',
            name='water_gate_map_url',
            field=models.URLField(blank=True, verbose_name='GoogleMapのURL'),
        ),
    ]
