# Generated by Django 4.2.5 on 2023-10-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_watergate_water_gate_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watergate',
            name='water_gate_map_url',
            field=models.TextField(max_length=512, verbose_name='GoogleMapのURL'),
        ),
    ]
