# Generated by Django 4.2.5 on 2023-10-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_watergate_water_gate_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watergate',
            name='water_gate_map_url',
            field=models.CharField(max_length=512, verbose_name='GoogleMapのIframeのsrc'),
        ),
    ]
